name: Build OVMF

on:
  workflow_dispatch:
    inputs:
      gop_url:
        description: 'URL for IntelGopDriver.efi'
        required: true
      vbt_url:
        description: 'URL for Vbt.bin'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Create GOP directory and download files
      run: |
        mkdir gop
        curl -L ${{ github.event.inputs.gop_url || secrets.GOP_URL }} -o gop/IntelGopDriver.efi
        curl -L ${{ github.event.inputs.vbt_url || secrets.VBT_URL }} -o gop/Vbt.bin

    - name: Build OVMF
      run: |
        bash build_ovmf.sh

    - name: Upload OVMF artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ovmf-files
        path: |
          edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd
          edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd

