name: Build OVMF

on:
  workflow_dispatch:
    inputs:
      vbt_url:
        description: 'URL to download VBT file'
        required: true
        type: string
      gop_url:
        description: 'URL to download GOP file'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create GOP directory
      run: mkdir -p gop

    - name: Download VBT and GOP files
      if: github.event_name == 'workflow_dispatch'
      run: |
        curl -L -o gop/Vbt.bin ${{ github.event.inputs.vbt_url }}
        curl -L -o gop/IntelGopDriver.efi ${{ github.event.inputs.gop_url }}

    - name: Check for VBT and GOP files
      run: |
        if [[ ! -f gop/Vbt.bin || ! -f gop/IntelGopDriver.efi ]]; then
          echo "Error: Vbt.bin or IntelGopDriver.efi not found in the gop directory."
          echo "Please ensure the URLs provided are correct and accessible."
          exit 1
        fi

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v1

    - name: Build OVMF
      run: |
        docker build -t ovmf-builder -f- . <<EOF
        FROM ubuntu:20.04
        RUN apt-get update && apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils
        WORKDIR /workspace
        COPY . .
        RUN mkdir -p edk2/OvmfPkg/IntelGop edk2/OvmfPkg/Vbt
        RUN cp gop/IntelGopDriver.efi edk2/OvmfPkg/IntelGop/IntelGopDriver.efi
        RUN cp gop/Vbt.bin edk2/OvmfPkg/Vbt/Vbt.bin
        RUN chmod +x build_ovmf.sh
        CMD ["./build_ovmf.sh"]
        EOF
        docker run --rm -v ${{ github.workspace }}:/workspace ovmf-builder

    - name: Upload OVMF.fd
      uses: actions/upload-artifact@v2
      with:
        name: OVMF.fd
        path: edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF.fd